parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaVersion: 2020
  sourceType: module
settings:
  react:
    version: detect
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
rules: {
  prettier/prettier: [2, { endOfLine: 'auto' }],
  '@typescript-eslint/no-explicit-any': 0,
  'no-return-await': 0,
  '@typescript-eslint/return-await': [error, never],
  '@typescript-eslint/restrict-template-expressions': 0,
  '@typescript-eslint/restrict-plus-operands': 0,
  '@typescript-eslint/no-unsafe-assignment': 0,
  '@typescript-eslint/no-unsafe-member-access': 0,
  '@typescript-eslint/explicit-module-boundary-access': 0,
  '@typescript-eslint/no-empty-function': 0,
  '@typescript-eslint/prefer-for-of': 2,
  'no-loop-func': 0,
  '@typescript-eslint/no-loop-func': 2,
}
